import { z } from "zod";

/**
 * Config for the SJMS5 (Student Journey Management System v5) adapter.
 * Reads directly from the Postgres schema generated by Prisma.
 */
export const Sjms5ConfigSchema = z.object({
  /** Postgres connection URL. Stored via secrets accessor in practice; field is the key. */
  databaseUrlSecretKey: z.string().min(1),
  /** Prisma schema name. Default "public". */
  schema: z.string().default("public"),
  /** Statement timeout ms. */
  statementTimeoutMs: z.number().int().positive().default(30_000),
  /** Limit applied to sampling queries. */
  sampleDefaultLimit: z.number().int().positive().default(100),
});

export type Sjms5Config = z.infer<typeof Sjms5ConfigSchema>;
